#!/bin/bash

# Reload system daemons
sudo systemctl daemon-reload

# Apply udev rules
sudo udevadm control --reload-rules
sudo udevadm trigger

# Add the user to the dialout group
sudo usermod -a -G dialout ${USER}

# Enable SSH server
sudo systemctl enable ssh.service

# Enable services for using RPi as an access point
# https://www.mikan-tech.net/entry/raspi-wifi-ap-sta
sudo systemctl unmask hostapd.service
sudo systemctl enable hostapd.service

# Setting up a routed wireless access point
# https://www.mikan-tech.net/entry/raspi-ap-sta-router
sudo iptables -t nat -A POSTROUTING -s 192.168.249.0/24 ! -d 192.168.249.0/24 -j MASQUERADE
sudo netfilter-persistent save

# Disable Bluetooth HCI (Host Controller Interface) to enable GPIO UART
sudo systemctl disable hciuart.service

# Disable swap because the access speed to SD card is too slow
sudo systemctl disable dphys-swapfile.service

# Disable NetworkManager to use wpa_supplicant
sudo systemctl disable NetworkManager.service

# Enable Tobas services
sudo systemctl enable tobas_real.target
