<?xml version="1.0"?>
<package format="3">

  <name>tobas_control_system</name>
  <version>0.0.0</version>
  <description>TODO</description>
  <maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>qtpositioning5-dev</depend>
  <depend>magic_enum_ament</depend>
  <depend>tobas_linux</depend>
  <depend>tobas_path_tools</depend>
  <depend>tobas_ros2_tools</depend>
  <depend>tobas_constants</depend>
  <depend>tobas_drone_core</depend>
  <depend>tobas_msgs_adapter</depend>
  <depend>tobas_qt_tools</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
