<?xml version="1.0"?>
<package format="2">

	<name>tobas_setup_assistant</name>
	<version>0.0.0</version>
	<description>TODO</description>
	<maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
	<license>TODO</license>

	<buildtool_depend>catkin</buildtool_depend>
	
	<depend>pyqt5-dev-tools</depend>

	<depend>rospy</depend>
	<depend>rviz</depend>
	<depend>joint_state_publisher</depend>
	<depend>joint_state_publisher_gui</depend>
	<depend>moveit_msgs</depend>

	<depend>dh_rqt_tools</depend>
	<depend>kdl_sympy</depend>
	<depend>urdf_tools_py</depend>
	<depend>tobas_rviz_plugin</depend>
	<depend>tobas_msgs</depend>

</package>
