#!/bin/bash

# control/Dependsに依存しないコマンドのみ記述できる

# Install ROS Noetic without using curl: https://gist.github.com/takurx/9ea1a664ec65c0822ca5ceb7288cb0c8
sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
