<?xml version="1.0"?>
<package format="3">

  <name>urdf_builder</name>
  <version>0.0.0</version>
  <description>The urdf_builder package</description>
  <maintainer email="denys.kotelovych@gmail.com">Denys Kotelovych</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>tobas_tools</depend>
  <depend>tobas_linux</depend>
  <depend>tobas_property_tools</depend>
  <depend>tobas_std_tools</depend>
  <depend>rviz</depend>
  <depend>pluginlib</depend>
  <depend>urdf</depend>
  <depend>roslaunch</depend>

  <export>
    <rviz plugin="${prefix}/plugin_description.xml"/>
  </export>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
