CommandLevel level

tobas_kdl_msgs/Vector pos    # Target global position [m]
tobas_kdl_msgs/Vector vel    # Target global linear velocity [m/s]
tobas_kdl_msgs/Vector acc    # Target global linear acceleration (feedforward) [m/s^2]

tobas_kdl_msgs/Euler rpy     # Target global orientation [rad]
tobas_kdl_msgs/Vector gyro   # Target local angular velocity [rad/s]
tobas_kdl_msgs/Vector dgyro  # Target local angular acceleration (feedforward) [rad/s^2]
