std_msgs/Header header
float64 roll      # CH1: [-1, 1]
float64 pitch     # CH2: [-1, 1]
float64 throttle  # CH3: [-1, 1]
float64 yaw       # CH4: [-1, 1]
bool enable       # CH5: Enable Radio Control
bool kill         # CH6: Kill Switch
uint8 mode        # CH7: Flight Mode
bool sub_mode     # CH8: Sub Flight Mode
bool gpsw1        # CH9: General Purpose Switch 1
bool gpsw2        # CH10: General Purpose Switch 2
