<?xml version="1.0"?>
<package format="3">

	<name>tobas_truncated_octahedron</name>
	<version>0.0.0</version>
	<description>Tobas meta package for truncated_octahedron</description>
	<maintainer email="example@gmail.com">example</maintainer>
	<license>BSD</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<exec_depend>tobas_truncated_octahedron_config</exec_depend>
	<exec_depend>tobas_truncated_octahedron_user_cpp</exec_depend>
	<exec_depend>tobas_truncated_octahedron_user_py</exec_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
