<package format="3">

	<name>tobas_t1_core</name>
	<version>0.0.0</version>
	<description>Collection of drivers and examples for Navio 2 - autopilot shield for Raspberry Pi.</description>
	<maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
	<license>TODO</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_linux</depend>
	<depend>tobas_std_tools</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
