<?xml version="1.0"?>
<package format="3">

  <name>tobas_setup_assistant</name>
  <version>0.0.0</version>
  <description>TODO</description>
  <maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>hardware_interface</depend>
  <depend>visualization_msgs</depend>
  <depend>moveit_msgs</depend>
  <depend>tobas_kdl_conversions</depend>
  <depend>tobas_linux</depend>
  <depend>tobas_property_tools</depend>
  <depend>tobas_tools</depend>
  <depend>tobas_drone_msgs_adapter</depend>
  <depend>tobas_qt_tools</depend>

  <exec_depend>xacro</exec_depend>
  <exec_depend>tobas_rviz_plugin</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
