<?xml version="1.0"?>
<package format="3">

  <name>tobas_setup_assistant</name>
  <version>0.0.0</version>
  <description>TODO</description>
  <maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>visualization_msgs</depend>
  <depend>moveit_msgs</depend>
  <depend>inja_ament</depend>
  <depend>rapidcsv_ament</depend>
  <depend>tobas_kdl_conversions</depend>
  <depend>tobas_ros2_tools</depend>
  <depend>tobas_property_client</depend>
  <depend>tobas_drone_msgs_adapter</depend>
  <depend>tobas_qt_tools</depend>
  <depend>tobas_gui_common</depend>

  <exec_depend>xacro</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>forward_command_controller</exec_depend>
  <exec_depend>hardware_interface</exec_depend>
  <exec_depend>gz_ros2_control</exec_depend>
  <exec_depend>tobas_rviz_plugin</exec_depend>
  <exec_depend>tobas_property_server</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
