<!-- SPDX-License-Identifier: GPL-3.0-or-later -->
<!-- Copyright (C) 2026 Tobas, Inc. -->
<package format="3">

	<name>d_roc_gamepad</name>
	<version>0.0.0</version>
	<description>D-ROC gamepad input package</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>
	<buildtool_depend>pkg-config</buildtool_depend>

	<build_depend>libevdev-dev</build_depend>
	<exec_depend>libevdev2</exec_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
