<?xml version="1.0"?>
<package format="3">

  <name>tobas_hardware_setup</name>
  <version>0.0.0</version>
  <description>TODO</description>
  <maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>tobas_drone_msgs_adapter</depend>
  <depend>tobas_hal_core</depend>
  <depend>tobas_hal_msgs_adapter</depend>
  <depend>tobas_real_common</depend>
  <depend>tobas_qt_tools</depend>
  <depend>tobas_gui_common</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
