<?xml version="1.0"?>
<package format="2">

	<name>tobas_mr_thrust_estimation</name>
	<version>0.0.0</version>
	<description>TODO</description>
	<maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
	<license>TODO</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>dynamic_reconfigure</depend>
	<depend>nodelet</depend>
	<depend>pluginlib</depend>

	<depend>tobas_linear_control</depend>
	<depend>tobas_mr_common</depend>

	<export>
		<nodelet plugin="${prefix}/nodelet_description.xml"/>
	</export>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
