<?xml version="1.0"?>
<package format="2">

	<name>tobas_tools</name>
	<version>0.0.0</version>
	<description>TODO</description>
	<maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
	<license>TODO</license>

	<buildtool_depend>catkin</buildtool_depend>

	<depend>tobas_msgs</depend>
	<depend>tobas_ros_tools</depend>
	<depend>tobas_kdl</depend>
	<depend>tobas_linear_control</depend>

</package>
