from .start import StartWidget
from .propellers import PropellersWidget
from .battery import BatteryWidget
from .imu import ImuWidget
from .magnetometer import MagnetometerWidget
from .barometer import BarometerWidget
from .gps import GpsWidget
from .depth_camera import DepthCameraWidget
from .lidar import LidarWidget
from .controller import ControllerWidget
from .simulation import SimulationWidget
from .author_information import AuthorInformationWidget
from .ros_package import RosPackageWidget
