from .start import StartWidget
from .propellers import PropellersWidget
from .imu import ImuWidget
from .magnetometer import MagnetometerWidget
from .barometer import BarometerWidget
from .gps import GpsWidget
from .perception_3d import Perception3dWidget
from .controllers import ControllersWidget
from .simulation import SimulationWidget
from .author_information import AuthorInformationWidget
from .ros_package import RosPackageWidget
