<package format="3">

  <name>tobas_gui_core</name>
  <version>0.0.0</version>
  <description>TODO</description>
  <maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>tobas_homepage</depend>
  <depend>tobas_urdf_builder</depend>
  <depend>tobas_setup_assistant</depend>
  <depend>tobas_hardware_setup</depend>
  <depend>tobas_control_system</depend>
  <depend>tobas_parameter_tuning_gui</depend>
  <depend>tobas_flight_log_gui</depend>
  <depend>tobas_simulation_gui</depend>

  <exec_depend>rmw_cyclonedds_cpp</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
