# インターフェースの設定
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0

# 使用するインターフェース名
interface=ap0

# ドライバインターフェースタイプ (hostap/wired/none/nl80211/bsd)
# デフォルトはhostapd
# nl80211はLinux mac80211ドライバで使われている
driver=nl80211

# WiFiのSSID
ssid=raspberry_wifi

# 国コードに基づいてチャネルと送信出力を制限
country_code=JP
ieee80211d=1
ieee80211h=1

# 802.11n (2.4GHz) を使用するための設定
hw_mode=g
ieee80211n=1
wmm_enabled=1
require_ht=1
ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40][DSSS_CCK-40]
channel=6
obss_interval=0

# 802.11ac (5GHz) を使用するための設定
# hw_mode=a
# ieee80211ac=1
# require_ht=1
# vht_capab=[SHORT-GI-80]
# channel=36
# vht_oper_chwidth=1
# vht_oper_centr_freq_seg0_idx=42

# 認証
auth_algs=1
wpa=2
wpa_passphrase=raspberry
wpa_key_mgmt=WPA-PSK
macaddr_acl=0

# AESベースのCCMP暗号化 (推奨)
wpa_pairwise=CCMP
rsn_pairwise=CCMP
