// Generated by gencpp from file tobas_msgs/JointCommandArray.msg
// DO NOT EDIT!

#ifndef TOBAS_MSGS_MESSAGE_JOINTCOMMANDARRAY_H
#define TOBAS_MSGS_MESSAGE_JOINTCOMMANDARRAY_H

#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include "./JointCommand.h"

namespace tobas_msgs
{
template <class ContainerAllocator>
struct JointCommandArray_
{
  typedef JointCommandArray_<ContainerAllocator> Type;

  JointCommandArray_() : header(), commands()
  {
  }
  JointCommandArray_(const ContainerAllocator& _alloc) : header(_alloc), commands(_alloc)
  {
    (void)_alloc;
  }

  typedef ::std_msgs::Header_<ContainerAllocator> _header_type;
  _header_type header;

  typedef std::vector<
    ::tobas_msgs::JointCommand_<ContainerAllocator>,
    typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<
      ::tobas_msgs::JointCommand_<ContainerAllocator>>>
    _commands_type;
  _commands_type commands;

  typedef boost::shared_ptr<::tobas_msgs::JointCommandArray_<ContainerAllocator>> Ptr;
  typedef boost::shared_ptr<::tobas_msgs::JointCommandArray_<ContainerAllocator> const> ConstPtr;

};  // struct JointCommandArray_

typedef ::tobas_msgs::JointCommandArray_<std::allocator<void>> JointCommandArray;

typedef boost::shared_ptr<::tobas_msgs::JointCommandArray> JointCommandArrayPtr;
typedef boost::shared_ptr<::tobas_msgs::JointCommandArray const> JointCommandArrayConstPtr;

// constants requiring out of line definition

template <typename ContainerAllocator>
std::ostream&
operator<<(std::ostream& s, const ::tobas_msgs::JointCommandArray_<ContainerAllocator>& v)
{
  ros::message_operations::Printer<::tobas_msgs::JointCommandArray_<ContainerAllocator>>::stream(
    s, "", v);
  return s;
}

template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(
  const ::tobas_msgs::JointCommandArray_<ContainerAllocator1>& lhs,
  const ::tobas_msgs::JointCommandArray_<ContainerAllocator2>& rhs)
{
  return lhs.header == rhs.header && lhs.commands == rhs.commands;
}

template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(
  const ::tobas_msgs::JointCommandArray_<ContainerAllocator1>& lhs,
  const ::tobas_msgs::JointCommandArray_<ContainerAllocator2>& rhs)
{
  return !(lhs == rhs);
}

}  // namespace tobas_msgs

namespace ros
{
namespace message_traits
{
template <class ContainerAllocator>
struct IsMessage<::tobas_msgs::JointCommandArray_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct IsMessage<::tobas_msgs::JointCommandArray_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::tobas_msgs::JointCommandArray_<ContainerAllocator>> : FalseType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::tobas_msgs::JointCommandArray_<ContainerAllocator> const> : FalseType
{
};

template <class ContainerAllocator>
struct HasHeader<::tobas_msgs::JointCommandArray_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader<::tobas_msgs::JointCommandArray_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct MD5Sum<::tobas_msgs::JointCommandArray_<ContainerAllocator>>
{
  static const char* value()
  {
    return "1ba01a5ef7b59067732218b693a16163";
  }

  static const char* value(const ::tobas_msgs::JointCommandArray_<ContainerAllocator>&)
  {
    return value();
  }
  static const uint64_t static_value1 = 0x1ba01a5ef7b59067ULL;
  static const uint64_t static_value2 = 0x732218b693a16163ULL;
};

template <class ContainerAllocator>
struct DataType<::tobas_msgs::JointCommandArray_<ContainerAllocator>>
{
  static const char* value()
  {
    return "tobas_msgs/JointCommandArray";
  }

  static const char* value(const ::tobas_msgs::JointCommandArray_<ContainerAllocator>&)
  {
    return value();
  }
};

template <class ContainerAllocator>
struct Definition<::tobas_msgs::JointCommandArray_<ContainerAllocator>>
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
           "tobas_msgs/JointCommand[] commands\n"
           "\n"
           "================================================================================\n"
           "MSG: std_msgs/Header\n"
           "# Standard metadata for higher-level stamped data types.\n"
           "# This is generally used to communicate timestamped data \n"
           "# in a particular coordinate frame.\n"
           "# \n"
           "# sequence ID: consecutively increasing ID \n"
           "uint32 seq\n"
           "#Two-integer timestamp that is expressed as:\n"
           "# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called "
           "'secs')\n"
           "# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called "
           "'nsecs')\n"
           "# time-handling sugar is provided by the client library\n"
           "time stamp\n"
           "#Frame this data is associated with\n"
           "string frame_id\n"
           "\n"
           "================================================================================\n"
           "MSG: tobas_msgs/JointCommand\n"
           "string name\n"
           "float64 data\n";
  }

  static const char* value(const ::tobas_msgs::JointCommandArray_<ContainerAllocator>&)
  {
    return value();
  }
};

}  // namespace message_traits
}  // namespace ros

namespace ros
{
namespace serialization
{
template <class ContainerAllocator>
struct Serializer<::tobas_msgs::JointCommandArray_<ContainerAllocator>>
{
  template <typename Stream, typename T>
  inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.commands);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
};  // struct JointCommandArray_

}  // namespace serialization
}  // namespace ros

namespace ros
{
namespace message_operations
{
template <class ContainerAllocator>
struct Printer<::tobas_msgs::JointCommandArray_<ContainerAllocator>>
{
  template <typename Stream>
  static void stream(
    Stream& s,
    const std::string& indent,
    const ::tobas_msgs::JointCommandArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer<::std_msgs::Header_<ContainerAllocator>>::stream(s, indent + "  ", v.header);
    s << indent << "commands[]" << std::endl;
    for (size_t i = 0; i < v.commands.size(); ++i)
    {
      s << indent << "  commands[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer<::tobas_msgs::JointCommand_<ContainerAllocator>>::stream(
        s, indent + "    ", v.commands[i]);
    }
  }
};

}  // namespace message_operations
}  // namespace ros

#endif  // TOBAS_MSGS_MESSAGE_JOINTCOMMANDARRAY_H
