// Generated by gencpp from file tobas_msgs/LinkState.msg
// DO NOT EDIT!

#ifndef TOBAS_MSGS_MESSAGE_LINKSTATE_H
#define TOBAS_MSGS_MESSAGE_LINKSTATE_H

#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tobas_kdl_msgs/Frame.h>
#include <tobas_kdl_msgs/Twist.h>
#include <tobas_kdl_msgs/Accel.h>
#include <tobas_kdl_msgs/Wrench.h>

namespace tobas_msgs
{
template <class ContainerAllocator>
struct LinkState_
{
  typedef LinkState_<ContainerAllocator> Type;

  LinkState_() : name(), frame(), twist(), accel(), wrench()
  {
  }
  LinkState_(const ContainerAllocator& _alloc)
    : name(_alloc), frame(_alloc), twist(_alloc), accel(_alloc), wrench(_alloc)
  {
    (void)_alloc;
  }

  /* ADDED */
  LinkState_(
    const std::string& _name,
    const kdl::Frame& _frame,
    const kdl::Twist& _twist,
    const kdl::Accel& _accel,
    const kdl::Wrench& _wrench)
    : name(_name), frame(_frame), twist(_twist), accel(_accel), wrench(_wrench)
  {
  }

  typedef std::basic_string<
    char,
    std::char_traits<char>,
    typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
    _name_type;
  _name_type name;

  typedef tobas_kdl_msgs::Frame_<ContainerAllocator> _frame_type;
  _frame_type frame;

  typedef tobas_kdl_msgs::Twist_<ContainerAllocator> _twist_type;
  _twist_type twist;

  typedef tobas_kdl_msgs::Accel_<ContainerAllocator> _accel_type;
  _accel_type accel;

  typedef tobas_kdl_msgs::Wrench_<ContainerAllocator> _wrench_type;
  _wrench_type wrench;

  typedef boost::shared_ptr<::tobas_msgs::LinkState_<ContainerAllocator>> Ptr;
  typedef boost::shared_ptr<::tobas_msgs::LinkState_<ContainerAllocator> const> ConstPtr;

};  // struct LinkState_

typedef ::tobas_msgs::LinkState_<std::allocator<void>> LinkState;

typedef boost::shared_ptr<::tobas_msgs::LinkState> LinkStatePtr;
typedef boost::shared_ptr<::tobas_msgs::LinkState const> LinkStateConstPtr;

// constants requiring out of line definition

template <typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tobas_msgs::LinkState_<ContainerAllocator>& v)
{
  ros::message_operations::Printer<::tobas_msgs::LinkState_<ContainerAllocator>>::stream(s, "", v);
  return s;
}

template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(
  const ::tobas_msgs::LinkState_<ContainerAllocator1>& lhs,
  const ::tobas_msgs::LinkState_<ContainerAllocator2>& rhs)
{
  return lhs.name == rhs.name && lhs.frame == rhs.frame && lhs.twist == rhs.twist && lhs.accel == rhs.accel
         && lhs.wrench == rhs.wrench;
}

template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(
  const ::tobas_msgs::LinkState_<ContainerAllocator1>& lhs,
  const ::tobas_msgs::LinkState_<ContainerAllocator2>& rhs)
{
  return !(lhs == rhs);
}

}  // namespace tobas_msgs

namespace ros
{
namespace message_traits
{
template <class ContainerAllocator>
struct IsMessage<::tobas_msgs::LinkState_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct IsMessage<::tobas_msgs::LinkState_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::tobas_msgs::LinkState_<ContainerAllocator>> : FalseType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::tobas_msgs::LinkState_<ContainerAllocator> const> : FalseType
{
};

template <class ContainerAllocator>
struct HasHeader<::tobas_msgs::LinkState_<ContainerAllocator>> : FalseType
{
};

template <class ContainerAllocator>
struct HasHeader<::tobas_msgs::LinkState_<ContainerAllocator> const> : FalseType
{
};

template <class ContainerAllocator>
struct MD5Sum<::tobas_msgs::LinkState_<ContainerAllocator>>
{
  static const char* value()
  {
    return "6edc4aac55dcc21f44c45f3e28e84e66";
  }

  static const char* value(const ::tobas_msgs::LinkState_<ContainerAllocator>&)
  {
    return value();
  }
  static const uint64_t static_value1 = 0x6edc4aac55dcc21fULL;
  static const uint64_t static_value2 = 0x44c45f3e28e84e66ULL;
};

template <class ContainerAllocator>
struct DataType<::tobas_msgs::LinkState_<ContainerAllocator>>
{
  static const char* value()
  {
    return "tobas_msgs/LinkState";
  }

  static const char* value(const ::tobas_msgs::LinkState_<ContainerAllocator>&)
  {
    return value();
  }
};

template <class ContainerAllocator>
struct Definition<::tobas_msgs::LinkState_<ContainerAllocator>>
{
  static const char* value()
  {
    return "string name\n"
           "tobas_kdl_msgs/Frame frame\n"
           "tobas_kdl_msgs/Twist twist\n"
           "tobas_kdl_msgs/Accel accel\n"
           "tobas_kdl_msgs/Wrench wrench\n"
           "\n"
           "================================================================================\n"
           "MSG: tobas_kdl_msgs/Frame\n"
           "tobas_kdl_msgs/Vector trans\n"
           "tobas_kdl_msgs/Rotation rot\n"
           "\n"
           "================================================================================\n"
           "MSG: tobas_kdl_msgs/Vector\n"
           "float64 x\n"
           "float64 y\n"
           "float64 z\n"
           "\n"
           "================================================================================\n"
           "MSG: tobas_kdl_msgs/Rotation\n"
           "float64[9] data\n"
           "\n"
           "================================================================================\n"
           "MSG: tobas_kdl_msgs/Twist\n"
           "tobas_kdl_msgs/Vector linear\n"
           "tobas_kdl_msgs/Vector angular\n"
           "\n"
           "================================================================================\n"
           "MSG: tobas_kdl_msgs/Accel\n"
           "tobas_kdl_msgs/Vector linear\n"
           "tobas_kdl_msgs/Vector angular\n"
           "\n"
           "================================================================================\n"
           "MSG: tobas_kdl_msgs/Wrench\n"
           "tobas_kdl_msgs/Vector force\n"
           "tobas_kdl_msgs/Vector torque\n";
  }

  static const char* value(const ::tobas_msgs::LinkState_<ContainerAllocator>&)
  {
    return value();
  }
};

}  // namespace message_traits
}  // namespace ros

namespace ros
{
namespace serialization
{
template <class ContainerAllocator>
struct Serializer<::tobas_msgs::LinkState_<ContainerAllocator>>
{
  template <typename Stream, typename T>
  inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.name);
    stream.next(m.frame);
    stream.next(m.twist);
    stream.next(m.accel);
    stream.next(m.wrench);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
};  // struct LinkState_

}  // namespace serialization
}  // namespace ros

namespace ros
{
namespace message_operations
{
template <class ContainerAllocator>
struct Printer<::tobas_msgs::LinkState_<ContainerAllocator>>
{
  template <typename Stream>
  static void stream(Stream& s, const std::string& indent, const ::tobas_msgs::LinkState_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<
      char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::
      stream(s, indent + "  ", v.name);
    s << indent << "frame: ";
    s << std::endl;
    Printer<tobas_kdl_msgs::Frame_<ContainerAllocator>>::stream(s, indent + "  ", v.frame);
    s << indent << "twist: ";
    s << std::endl;
    Printer<tobas_kdl_msgs::Twist_<ContainerAllocator>>::stream(s, indent + "  ", v.twist);
    s << indent << "accel: ";
    s << std::endl;
    Printer<tobas_kdl_msgs::Accel_<ContainerAllocator>>::stream(s, indent + "  ", v.accel);
    s << indent << "wrench: ";
    s << std::endl;
    Printer<tobas_kdl_msgs::Wrench_<ContainerAllocator>>::stream(s, indent + "  ", v.wrench);
  }
};

}  // namespace message_operations
}  // namespace ros

#endif  // TOBAS_MSGS_MESSAGE_LINKSTATE_H
