// Generated by gencpp from file tobas_msgs/LinkStateArray.msg
// DO NOT EDIT!

#ifndef TOBAS_MSGS_MESSAGE_LINKSTATEARRAY_H
#define TOBAS_MSGS_MESSAGE_LINKSTATEARRAY_H

#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tobas_msgs/LinkState.h>

namespace tobas_msgs
{
template <class ContainerAllocator>
struct LinkStateArray_
{
  typedef LinkStateArray_<ContainerAllocator> Type;

  LinkStateArray_() : header(), states()
  {
  }
  LinkStateArray_(const ContainerAllocator& _alloc) : header(_alloc), states(_alloc)
  {
    (void)_alloc;
  }

  typedef ::std_msgs::Header_<ContainerAllocator> _header_type;
  _header_type header;

  typedef std::vector<
    ::tobas_msgs::LinkState_<ContainerAllocator>,
    typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<
      ::tobas_msgs::LinkState_<ContainerAllocator>>>
    _states_type;
  _states_type states;

  typedef boost::shared_ptr<::tobas_msgs::LinkStateArray_<ContainerAllocator>> Ptr;
  typedef boost::shared_ptr<::tobas_msgs::LinkStateArray_<ContainerAllocator> const> ConstPtr;

  /* ADDED: Returns the link names. */
  std::vector<std::string> names() const
  {
    std::vector<std::string> res;
    for (const auto& state : states)
      res.push_back(state.name);
    return res;
  }
};  // struct LinkStateArray_

typedef ::tobas_msgs::LinkStateArray_<std::allocator<void>> LinkStateArray;

typedef boost::shared_ptr<::tobas_msgs::LinkStateArray> LinkStateArrayPtr;
typedef boost::shared_ptr<::tobas_msgs::LinkStateArray const> LinkStateArrayConstPtr;

// constants requiring out of line definition

template <typename ContainerAllocator>
std::ostream&
operator<<(std::ostream& s, const ::tobas_msgs::LinkStateArray_<ContainerAllocator>& v)
{
  ros::message_operations::Printer<::tobas_msgs::LinkStateArray_<ContainerAllocator>>::stream(
    s, "", v);
  return s;
}

template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(
  const ::tobas_msgs::LinkStateArray_<ContainerAllocator1>& lhs,
  const ::tobas_msgs::LinkStateArray_<ContainerAllocator2>& rhs)
{
  return lhs.header == rhs.header && lhs.states == rhs.states;
}

template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(
  const ::tobas_msgs::LinkStateArray_<ContainerAllocator1>& lhs,
  const ::tobas_msgs::LinkStateArray_<ContainerAllocator2>& rhs)
{
  return !(lhs == rhs);
}

}  // namespace tobas_msgs

namespace ros
{
namespace message_traits
{
template <class ContainerAllocator>
struct IsMessage<::tobas_msgs::LinkStateArray_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct IsMessage<::tobas_msgs::LinkStateArray_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::tobas_msgs::LinkStateArray_<ContainerAllocator>> : FalseType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::tobas_msgs::LinkStateArray_<ContainerAllocator> const> : FalseType
{
};

template <class ContainerAllocator>
struct HasHeader<::tobas_msgs::LinkStateArray_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader<::tobas_msgs::LinkStateArray_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct MD5Sum<::tobas_msgs::LinkStateArray_<ContainerAllocator>>
{
  static const char* value()
  {
    return "c5c28c0bb3da9e0207847d26ea12b178";
  }

  static const char* value(const ::tobas_msgs::LinkStateArray_<ContainerAllocator>&)
  {
    return value();
  }
  static const uint64_t static_value1 = 0xc5c28c0bb3da9e02ULL;
  static const uint64_t static_value2 = 0x07847d26ea12b178ULL;
};

template <class ContainerAllocator>
struct DataType<::tobas_msgs::LinkStateArray_<ContainerAllocator>>
{
  static const char* value()
  {
    return "tobas_msgs/LinkStateArray";
  }

  static const char* value(const ::tobas_msgs::LinkStateArray_<ContainerAllocator>&)
  {
    return value();
  }
};

template <class ContainerAllocator>
struct Definition<::tobas_msgs::LinkStateArray_<ContainerAllocator>>
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
           "tobas_msgs/LinkState[] states\n"
           "\n"
           "================================================================================\n"
           "MSG: std_msgs/Header\n"
           "# Standard metadata for higher-level stamped data types.\n"
           "# This is generally used to communicate timestamped data \n"
           "# in a particular coordinate frame.\n"
           "# \n"
           "# sequence ID: consecutively increasing ID \n"
           "uint32 seq\n"
           "#Two-integer timestamp that is expressed as:\n"
           "# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called "
           "'secs')\n"
           "# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called "
           "'nsecs')\n"
           "# time-handling sugar is provided by the client library\n"
           "time stamp\n"
           "#Frame this data is associated with\n"
           "string frame_id\n"
           "\n"
           "================================================================================\n"
           "MSG: tobas_msgs/LinkState\n"
           "string name\n"
           "tobas_kdl_msgs/Frame frame\n"
           "tobas_kdl_msgs/Twist twist\n"
           "tobas_kdl_msgs/Accel accel\n"
           "tobas_kdl_msgs/Wrench wrench\n"
           "\n"
           "================================================================================\n"
           "MSG: tobas_kdl_msgs/Frame\n"
           "tobas_kdl_msgs/Vector trans\n"
           "tobas_kdl_msgs/Rotation rot\n"
           "\n"
           "================================================================================\n"
           "MSG: tobas_kdl_msgs/Vector\n"
           "float64 x\n"
           "float64 y\n"
           "float64 z\n"
           "\n"
           "================================================================================\n"
           "MSG: tobas_kdl_msgs/Rotation\n"
           "float64[9] data\n"
           "\n"
           "================================================================================\n"
           "MSG: tobas_kdl_msgs/Twist\n"
           "tobas_kdl_msgs/Vector linear\n"
           "tobas_kdl_msgs/Vector angular\n"
           "\n"
           "================================================================================\n"
           "MSG: tobas_kdl_msgs/Accel\n"
           "tobas_kdl_msgs/Vector linear\n"
           "tobas_kdl_msgs/Vector angular\n"
           "\n"
           "================================================================================\n"
           "MSG: tobas_kdl_msgs/Wrench\n"
           "tobas_kdl_msgs/Vector force\n"
           "tobas_kdl_msgs/Vector torque\n";
  }

  static const char* value(const ::tobas_msgs::LinkStateArray_<ContainerAllocator>&)
  {
    return value();
  }
};

}  // namespace message_traits
}  // namespace ros

namespace ros
{
namespace serialization
{
template <class ContainerAllocator>
struct Serializer<::tobas_msgs::LinkStateArray_<ContainerAllocator>>
{
  template <typename Stream, typename T>
  inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.states);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
};  // struct LinkStateArray_

}  // namespace serialization
}  // namespace ros

namespace ros
{
namespace message_operations
{
template <class ContainerAllocator>
struct Printer<::tobas_msgs::LinkStateArray_<ContainerAllocator>>
{
  template <typename Stream>
  static void stream(
    Stream& s,
    const std::string& indent,
    const ::tobas_msgs::LinkStateArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer<::std_msgs::Header_<ContainerAllocator>>::stream(s, indent + "  ", v.header);
    s << indent << "states[]" << std::endl;
    for (size_t i = 0; i < v.states.size(); ++i)
    {
      s << indent << "  states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer<::tobas_msgs::LinkState_<ContainerAllocator>>::stream(
        s, indent + "    ", v.states[i]);
    }
  }
};

}  // namespace message_operations
}  // namespace ros

#endif  // TOBAS_MSGS_MESSAGE_LINKSTATEARRAY_H
