# cf. /usr/share/doc/hostapd/examples/hostapd.conf

# インターフェースの設定
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0

# 使用するインターフェース名
interface=ap0

# ドライバインターフェースタイプ (hostap/wired/none/nl80211/bsd)
# デフォルトはhostapd
# nl80211はLinux mac80211ドライバで使われている
driver=nl80211

# WiFiのSSID
ssid=raspberry_wifi

# 認証
auth_algs=1
wpa=2
wpa_passphrase=raspberry
wpa_key_mgmt=WPA-PSK
macaddr_acl=0

# AESベースのCCMP暗号化 (推奨)
wpa_pairwise=CCMP
rsn_pairwise=CCMP

# 国コード
country_code=JP

# 国コードに基づいてチャネルと送信出力を制限
ieee80211d=1

# DFSサポート
ieee80211h=1

# Wi-Fi Multimedia を有効化
# 優先順位をつけて通信の品質を上げる
wmm_enabled=1

# 干渉を避けるために最小の20MHz幅に固定
ht_capab=[HT20]

# 2.4GHzモード固有の設定
# 干渉を避けるためにOverlapping BSSスキャンを有効化
# hw_mode=g
# ieee80211n=1
# channel=6
# channelist=1 6 11
# obss_interval=100

# 5GHzモード固有の設定
# 屋外で使用可能なW56に該当するチャネルのみ使用
# 帯域幅を20 or 40MHzに限定
hw_mode=a
ieee80211ac=1
channel=100
chanlist=100 104 108 112 116 120 124 128 132 136 140
vht_oper_chwidth=0
