int32 roll_left
int32 roll_right
int32 pitch_up
int32 pitch_down
int32 yaw_left
int32 yaw_right
int32 thrust_up
int32 thrust_down
int32 mode_auto
int32 mode_position
int32 mode_sport
int32 estop_on
int32 estop_off
int32 gpsw_on
int32 gpsw_off
---
bool success
string message
