from .start import StartWidget
from .battery import BatteryWidget
from .propulsion_system import PropulsionSystemWidget
from .fixed_wing.fixed_wing import FixedWingWidget
from .custom_joints import CustomJointsWidget
from .imu import ImuWidget
from .barometer import BarometerWidget
from .gps import GpsWidget
from .rgb_camera import RgbCameraWidget
from .depth_camera import DepthCameraWidget
from .lidar import LidarWidget
from .odometry import OdometryWidget
from .tether_station import TetherStationWidget
from .controller import ControllerWidget
from .observer import ObserverWidget
from .simulation import SimulationWidget
from .author_information import AuthorInformationWidget
from .ros_package import RosPackageWidget
