from .base_setting import BaseSettingWidget
from .start import StartWidget
from .battery import BatteryWidget
from .propulsion_system import PropulsionSystemWidget
from .fixed_wing.fixed_wing import FixedWingWidget
from .custom_joints import CustomJointsWidget
from .imu import ImuWidget
from .magnetometer import MagnetometerWidget
from .barometer import BarometerWidget
from .gps import GpsWidget
from .controller import ControllerWidget
from .observer import ObserverWidget
from .hardware import HardwareWidget
from .simulation import SimulationWidget
from .author_information import AuthorInformationWidget
from .ros_package import RosPackageWidget
