from .start import StartWidget
from .rotary_wings import RotaryWingsWidget
from .battery import BatteryWidget
from .imu import ImuWidget
from .magnetometer import MagnetometerWidget
from .barometer import BarometerWidget
from .gps import GpsWidget
from .rgb_camera import RgbCameraWidget
from .depth_camera import DepthCameraWidget
from .lidar import LidarWidget
from .controller import ControllerWidget
from .observer import ObserverWidget
from .simulation import SimulationWidget
from .author_information import AuthorInformationWidget
from .ros_package import RosPackageWidget
