<?xml version="1.0"?>
<package format="3">

	<name>tobas_third_party</name>
	<version>0.0.0</version>
	<description>TODO</description>
	<maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
	<license>TODO</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<exec_depend>inja_ament</exec_depend>
	<exec_depend>magic_enum_ament</exec_depend>
	<exec_depend>rapidcsv_ament</exec_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
