# Goal
tobas_command_msgs/CommandLevel level

float64 target_latitude          # [deg]
float64 target_longitude         # [deg]
float64 target_altitude          # [m]

float64 max_horizontal_velocity  # [m/s]
float64 max_vertical_velocity    # [m/s]
float64 max_horizontal_accel     # [m/s^2]
float64 max_vertical_accel       # [m/s^2]
float64 max_horizontal_jerk      # [m/s^3]
float64 max_vertical_jerk        # [m/s^3]

float64 acceptance_radius        # [m] By default, the acceptance radius is infinite.
float64 timeout                  # [s] Timeout after command duration. By default, timeout is infinite.

---

# Result
string message

---

# Feedback
geometry_msgs/Vector3 target_position   # [m]
geometry_msgs/Vector3 current_position  # [m]
geometry_msgs/Vector3 position_error    # [m]
