# goal
duration time_window

float64 horizontal_position_variance_threshold  # [m]
float64 vertical_position_variance_threshold    # [m]
float64 heading_variance_threshold              # [rad]
float64 attitude_threshold                      # [rad]
float64 velocity_threshold                      # [m/s]

---

# result
tobas_msgs/Odometry odom

int8 error_code
int8 NO_ERROR = 0
int8 INVALID_GOAL = -1
int8 PREEMPTED = -2
int8 UNKNOWN_ERROR = -3

---

# feedback
