<?xml version="1.0"?>
<package format="3">

	<name>tobas_ros2_tools</name>
	<version>0.0.0</version>
	<description>TODO</description>
	<maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
	<license>TODO</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>rclcpp</depend>
	<depend>ament_index_cpp</depend>
	<depend>tf2_ros</depend>
	<depend>tobas_std_tools</depend>
	<depend>tobas_string_tools</depend>
	<depend>tobas_path_tools</depend>

	<exec_depend>ros2launch</exec_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
