<?xml version="1.0"?>
<package format="2">

	<name>state_estimation_cascade</name>
	<version>0.0.0</version>
	<description>TODO</description>
	<maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
	<license>TODO</license>

	<buildtool_depend>catkin</buildtool_depend>

	<depend>roscpp</depend>
	<depend>orocos_kdl</depend>
	<depend>orientation_estimation_complement</depend>

	<depend>dh_std_tools</depend>
	<depend>dh_eigen_tools</depend>
	<depend>dh_ros_tools</depend>
	<depend>dh_linear_control</depend>

	<depend>multirotor_tools</depend>
	<depend>multirotor_msgs</depend>

</package>
