# Delays sending DHCPOFFER and proxydhcp replies for at least the specified number of seconds.
dhcp-mac=set:client_is_a_pi,B8:27:EB:*:*:*
dhcp-reply-delay=tag:client_is_a_pi,2

# Settings for DHCP server
interface=ap0
dhcp-range=192.168.249.50,192.168.249.150,255.255.255.0,12h
