send host-name = gethostname();
request subnet-mask, broadcast-address, time-offset, routers, domain-name, domain-name-servers, domain-search, host-name, dhcp6.name-servers, dhcp6.domain-search, dhcp6.fqdn, dhcp6.sntp-servers, netbios-name-servers, netbios-scope, interface-mtu, rfc3442-classless-static-routes, ntp-servers;

timeout 5;  # network.targetの達成時間を短くするために1回目のIP取得を早めに打ち切る
retry 20;   # その後は短い周期でIP取得を再試行
