#!/bin/bash

# Check user and host
if [ "$(id -un)" != "pi" ] || [ "$(hostname -s)" != "tobas" ]; then
  echo "This script can only be executed on RPi." >&2
  exit 1
fi

# Remove unnecessary files
sudo rm -rf /tmp/*
sudo rm -rf /var/tmp/*
sudo rm -rf /var/log/*
sudo rm -rf ~/.ros/*
rm -rf ~/.cache/*
rm -rf ~/.emacs.d/*
rm -rf ~/.vscode-server/*
rm ~/.bash_history*
rm ~/.python_history*

# Remove personal information
rm -rf ~/.gnupg/*
rm -rf ~/.ssh/*

# Clean tobas directory
sudo rm /etc/tobas/config/*.json
sudo rm -rf /etc/tobas/rosbag/*

# Clean user workspace
cd /etc/tobas/colcon_ws/
sudo colcon clean workspace -y
sudo rm -rf ./src/*

# Clear network settings
sudo sed -i '4,$ d' /etc/wpa_supplicant/wpa_supplicant.conf
if [ $? -ne 0 ]; then
  echo "Failed to edit /etc/wpa_supplicant/wpa_supplicant.conf." >&2
  exit 1
fi

echo -e "\033[32mCleaning finished successfully.\033[0m"
