#!/bin/bash

# Remove unnecessary files
sudo rm -rf /tmp/*
sudo rm -rf /var/tmp/*
sudo rm -rf /var/log/*
rm -rf ~/.cache/*
rm -rf ~/.emacs.d/*
rm -rf ~/.vscode-server/*
rm -rf ~/.ros/*
rm .bash_history*

# Remove personal information
rm -rf ~/.gnupg/*
rm -rf ~/.ssh/*

# Remove developer workspace
sudo rm ~/colcon_ws

# Clean user workspace
cd /etc/tobas/colcon_ws/
sudo colcon clean workspace -y
sudo rm -rf ./src/*

# Clear network settings
sudo sed -i '4,$ d' /etc/wpa_supplicant/wpa_supplicant.conf
if [ $? -ne 0 ]; then
  echo "Failed to edit /etc/wpa_supplicant/wpa_supplicant.conf."
  exit 1
fi

echo -e "\033[32mCleaning finished successfully.\033[0m"
