#!/bin/bash

# Tobasリポジトリの親ディレクトリに移動
cd $(realpath $(dirname "$0"))/../../../

# Gitが追跡しているファイルのみリモートと同期
rsync -av --delete --exclude-from=./tobas/.gitignore --exclude .git/ ./tobas pi@tobas:~/colcon_ws/src/
