#!/bin/bash

# Install Tobas
PARDIR=$(realpath $(dirname "$0"))
bash ${PARDIR}/tobas_build_release_upto tobas
if [$? -ne 0]; then
  echo "Failed to build."
  exit 1
fi

# Remove unnecessary files
sudo rm -rf /tmp/*
sudo rm -rf /var/tmp/*
sudo rm -rf /var/log/*
rm -rf ~/.cache/*
rm -rf ~/.emacs.d/*
rm -rf ~/.vscode-server/*
rm -rf ~/.ros/*

# Remove personal information
rm -rf ~/.gnupg/*
rm -rf ~/.ssh/*

# Clean user workspace
cd /etc/tobas/colcon_ws/
sudo colcon clean workspace -y
sudo rm -rf ./src/*

# Clear network settings
sudo sed -i '4,$ d' /etc/wpa_supplicant/wpa_supplicant.conf
if [$? -ne 0]; then
  echo "Failed to edit /etc/wpa_supplicant/wpa_supplicant.conf."
  exit 1
fi

echo -e "\033[32mFinished successfully.\033[0m"
