#!/bin/bash

# Check user and host
if [ "$(id -un)" != "pi" ] || [ "$(hostname -s)" != "tobas" ]; then
  echo "This script can only be executed on RPi." >&2
  exit 1
fi

# Set paths
COLCON_WS=~/colcon_ws
RELEASE_DIR=${COLCON_WS}/release
INSTALL_BASE=${RELEASE_DIR}/install

sudo rm -rf /opt/tobas # 一旦削除しないとsourceが反映されないことがあった
sudo cp -r ${INSTALL_BASE} /opt/tobas
if [ $? -ne 0 ]; then
  echo "Failed to copy ${INSTALL_BASE} to /opt/tobas." >&2
  exit 1
fi

echo -e "\033[32mInstallation finished successfully.\033[0m"
