#!/bin/bash

export COLCON_WS=~/colcon_ws
PARDIR=$(realpath $(dirname "$0"))

# Update repositories
cd ${COLCON_WS}
vcs pull
if [ $? -ne 0 ]; then
  echo "Failed to update repositories."
  exit 1
fi

# Build Tobas
bash ${PARDIR}/tobas_build_release_upto $1
if [ $? -ne 0 ]; then
  echo "Failed to build."
  exit 1
fi

# Install Tobas
bash ${PARDIR}/tobas_install
if [ $? -ne 0 ]; then
  echo "Failed to install."
  exit 1
fi

echo -e "\033[32mDeployment finished successfully.\033[0m"
