#!/bin/bash

set -e

# Check username.
if [ "$(id -un)" != "pi" ]; then
  echo "This script can only be executed on RPi." >&2
  exit 1
fi

# Show usage.
if [ $# -lt 1 ]; then
  echo "Usage: $(basename "$0") <package>" >&2
  exit 1
fi

# Stop the systemd service.
sudo systemctl stop tobas_real.target

# Navigate to the colcon workspace.
cd ~/colcon_ws/

# Limit the number of threads used to build a single package.
export MAKEFLAGS="-j1"

# Build and install the specified package and its dependencies.
sudo bash -c '
source /opt/ros/jazzy/setup.bash && \
colcon build \
  --merge-install \
  --parallel-workers 1 \
  --install-base /opt/tobas \
  --cmake-args \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_FLAGS="-mcpu=native" \
    -DCMAKE_CXX_FLAGS="-mcpu=native" \
  --packages-up-to $1 \
'

# Restart the systemd service.
sudo systemctl restart tobas_real.target

echo -e "\033[32mDeployment finished successfully.\033[0m"
