#!/bin/bash

# Check username
if [ "$(id -un)" != "pi" ]; then
  echo "This script can only be executed on RPi." >&2
  exit 1
fi

# Clean apt cache
sudo apt clean

# Remove unnecessary files
sudo rm -rf /srv/*
sudo rm -rf /tmp/*
sudo rm -rf /var/backups/*
sudo rm -rf /var/log/*
sudo rm -rf /var/tmp/*
sudo rm -rf /var/lib/apt/lists/*

# Clean tobas directory
sudo rm /etc/tobas/config/*
sudo rm -rf /etc/tobas/rosbag/*

# Clean user workspace
cd /etc/tobas/colcon_ws/
sudo colcon clean workspace -y
sudo rm -rf ./src/*

# Clear Wi-Fi client settings
sudo sed -i '4,$ d' /etc/wpa_supplicant/wpa_supplicant-nl80211-wlan0.conf
if [ $? -ne 0 ]; then
  echo "Failed to edit the wpa_supplicant configuration file." >&2
  exit 1
fi

# Clear Wi-Fi hotspot settings
sudo rm /etc/hostapd/hostapd.conf*

# Disable Tobas service
sudo systemctl disable tobas_real.target

echo -e "\033[32mCleaning finished successfully.\033[0m"
