#!/bin/bash

# Check user and host
if [ "$(id -un)" = "pi" ] && [ "$(hostname -s)" = "tobas" ]; then
  echo "This script cannot be executed on RPi." >&2
  exit 1
fi

# Tobasリポジトリの親ディレクトリに移動
cd $(realpath $(dirname "$0"))/../../../

# Gitが追跡しているファイルのみリモートと同期
rsync -av --delete --exclude-from=./tobas/.gitignore --exclude .git/ ./tobas pi@tobas:~/colcon_ws/src/
