# goal
tobas_msgs/CommandLevel level

---

# result
tobas_msgs/PositionYaw last_command

int8 error_code
int8 NO_ERROR = 0
int8 NOT_READY = -1
int8 INVALID_GOAL = -2
int8 PREEMPTED = -3
int8 UNKNOWN_ERROR = -4

---

# feedback
