<?xml version="1.0"?>
<package format="3">

	<name>tobas_mavros_bridge</name>
	<version>0.0.0</version>
	<description>TODO</description>
	<maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
	<license>TODO</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>roscpp</depend>
	<depend>nodelet</depend>
	<depend>pluginlib</depend>
	<depend>mavros</depend>
	<depend>mavros_extras</depend>

	<depend>tobas_tools</depend>

	<export>
		<nodelet plugin="${prefix}/nodelet_description.xml"/>
	</export>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
