<?xml version="1.0"?>
<package format="3">

	<name>tobas_gazebo_plugins</name>
	<version>0.0.0</version>
	<description>TODO</description>
	<maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
	<license>TODO</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>sensor_msgs</depend>
	<depend>geometry_msgs</depend>
	<depend>std_srvs</depend>
	<depend>laser_geometry</depend>
	<depend>tobas_dsp</depend>
	<depend>tobas_kdl</depend>
	<depend>tobas_path_tools</depend>
	<depend>tobas_ros2_tools</depend>
	<depend>tobas_node</depend>
	<depend>tobas_msgs</depend>
	<depend>tobas_gazebo_common</depend>
	<depend>tobas_gazebo_tools</depend>
	<depend>tobas_gazebo_msgs</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
