std_msgs/Header header

bool ok

uint8 rt_violation
uint8 battery_voltage_too_low
uint8 cpu_temperature_too_high
uint8 rotor_communication_error
uint8 attitude_too_steep
uint8 position_unstable
uint8 position_inaccurate
uint8 velocity_inaccurate
uint8 attitude_inaccurate
uint8 heading_inaccurate
uint8 mag_offset_too_large
uint8 mag_misalignment
uint8 vibration_too_high

uint8 PASSED = 0
uint8 FAILED = 1
uint8 IGNORED = 2
uint8 UNKNOWN = 3
