<?xml version="1.0"?>
<package format="2">

	<name>tobas_dynamixel</name>
	<version>0.0.0</version>
	<description>TODO</description>
	<maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
	<license>TODO</license>

	<buildtool_depend>catkin</buildtool_depend>

	<exec_depend>tobas_dynamixel_handler</exec_depend>
	<exec_depend>tobas_dynamixel_msgs</exec_depend>

	<export>
		<metapackage/>
	</export>

</package>
