voliro_like:
  controller_manager:
    ros__parameters:
      update_rate: 100
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      arm_0_joint_controller:
        type: forward_command_controller/ForwardCommandController
      arm_1_joint_controller:
        type: forward_command_controller/ForwardCommandController
      arm_2_joint_controller:
        type: forward_command_controller/ForwardCommandController
      arm_3_joint_controller:
        type: forward_command_controller/ForwardCommandController
      arm_4_joint_controller:
        type: forward_command_controller/ForwardCommandController
      arm_5_joint_controller:
        type: forward_command_controller/ForwardCommandController
