#!/bin/bash

# Disable unecessary services
# See: `$ systemd-analyze blame`
sudo systemctl disable exim4.service
sudo systemctl disable ModemManager.service
sudo systemctl disable lm-sensors.service

# Reload system daemons
sudo systemctl daemon-reload

# Apply udev rules
sudo udevadm control --reload-rules
sudo udevadm trigger

# Enable SSH server
sudo systemctl enable ssh.service

# Enable services for using RPi as an access point
# https://www.mikan-tech.net/entry/raspi-wifi-ap-sta
sudo systemctl unmask hostapd.service
sudo systemctl enable hostapd.service

# Setting up a routed wireless access point
# https://www.mikan-tech.net/entry/raspi-ap-sta-router
sudo iptables -t nat -A POSTROUTING -s 192.168.249.0/24 ! -d 192.168.249.0/24 -j MASQUERADE
sudo netfilter-persistent save

# Use WPA Supplicant instead of NetworkManager
sudo systemctl disable NetworkManager.service
sudo systemctl enable wpa_supplicant-nl80211@wlan0.service
