#!/bin/bash

# Reload system daemons
sudo systemctl daemon-reload

# Apply udev rules
sudo udevadm control --reload-rules
sudo udevadm trigger

# Add the user to the dialout group
sudo usermod -a -G dialout ${USER}

# Enable and restart services for using RPi as an access point
# https://www.mikan-tech.net/entry/raspi-wifi-ap-sta
sudo systemctl unmask hostapd.service
sudo systemctl enable hostapd.service
sudo systemctl restart hostapd.service
sudo systemctl restart dhcpcd.service
sudo systemctl restart dnsmasq.service

# Setting up a routed wireless access point
# https://www.mikan-tech.net/entry/raspi-ap-sta-router
sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -t nat -A POSTROUTING -s 192.168.249.0/24 ! -d 192.168.249.0/24 -j MASQUERADE
sudo netfilter-persistent save

# Create catkin workspace for Tobas configuration packages
sudo mkdir -p /etc/tobas/catkin_ws/src
cd /etc/tobas/catkin_ws
sudo catkin init

# Enable and restart Tobas services
sudo systemctl enable tobas_roscore.service
sudo systemctl enable tobas_fkie_master.service
sudo systemctl enable tobas_real.service
sudo systemctl restart tobas_roscore.service
sudo systemctl restart tobas_fkie_master.service
sudo systemctl restart tobas_real.service
