<package format="3">

	<name>tobas_wind_model</name>
	<version>0.0.0</version>
	<description>TODO</description>
	<maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
	<license>TODO</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_std_tools</depend>
	<depend>tobas_constants</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
