<package format="3">

	<name>tobas_voliro_like_user_cpp</name>
	<version>0.0.0</version>
	<description>Tobas user C++ package for voliro_like</description>
	<maintainer email="example@gmail.com">example</maintainer>
	<license>BSD</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>rclcpp</depend>
	<depend>rclcpp_components</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
