<package format="3">

	<name>tobas_drone_tools</name>
	<version>0.0.0</version>
	<description>TODO</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_drone_core</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
