// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Tobas, Inc.

#pragma once

#include "./tree_id_solver.hpp"

namespace tobas
{
namespace kdl
{
/**
 * @brief Tree version of `kdl::ChainDynParam`.
 */
class TreeDynParam : public TreeSolverI
{
  using super = TreeSolverI;

public:
  explicit TreeDynParam(const Tree& tree, const Vector& grav = Vector(0.0, 0.0, -st::kGravity));

  void updateInternalDataStructures() override;

  /**
   * @brief Compute the torque generated by Coriolis force.
   *
   * @param q Joint angles.
   * @param qd Joint angular velocities.
   */
  const JntArray& jntToCoriolis(const JntArray& q, const JntArray& qd);

  /**
   * @brief Compute the torque generated by gravity.
   *
   * @param q Joint angles.
   */
  const JntArray& jntToGravity(const JntArray& q);

private:
  TreeIdSolver rne_coriolis_;
  TreeIdSolver rne_gravity_;

  JntArray q_zero_;

  void resize();
};
}  // namespace kdl
}  // namespace tobas
