# Request
float64 mean_speed         # [m/s] Average wind speed at 20ft above ground
float64 direction          # [rad] Wind direction (yaw angle)
float64 gust_speed_factor  # [-] Ratio of gust wind speed to steady wind speed
float64 gust_duration      # [s] Duration of the gust
float64 gust_interval      # [s] Interval between gusts

---

# Response
bool success

# 設定された値
float64 mean_speed
float64 direction
float64 gust_speed_factor
float64 gust_duration
float64 gust_interval
