# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Tobas, Inc.

# Goal
tobas_mission_msgs/MissionItem[] items
tobas_mission_msgs/Priority priority

---

# Result
tobas_mission_msgs/ErrorCode error_code
string error_message

---

# Feedback
uint32 current_index
