<package format="3">

  <name>tobas_rviz_plugin</name>
  <version>0.0.0</version>
  <description>TODO</description>
  <maintainer email="masa0u0masa1215@gmail.com">Masayoshi Dohi</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>eigen_stl_containers</depend>
  <depend>angles</depend>
  <depend>geometric_shapes</depend>
  <depend>tf2_eigen</depend>
  <depend>rsl</depend>
  <depend>octomap_msgs</depend>
  <depend>rviz_common</depend>
  <depend>rviz_default_plugins</depend>
  <depend>rviz_rendering</depend>
  <depend>srdfdom</depend>
  <depend>tobas_visualization_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
    <rviz plugin="${prefix}/rviz_plugin_description.xml"/>
  </export>

</package>
